#!/bin/bash

# Create symlinks for files/dirs under /config

# if /config/youtube-dl.conf exists, symlink to /etc/youtube-dl.conf
if [[ -e "/config/youtube-dl.conf" ]]; then
    # if the symlink already exists, remove it
    if [[ -L "/etc/youtube-dl.conf" ]]; then
        rm -v "/etc/youtube-dl.conf"
    fi
    # create symlink
    ln -vs "/config/youtube-dl.conf" "/etc/youtube-dl.conf" > /dev/null 2>&1 || true
fi

# if /config/.netrc exists, symlink to /home/dockeruser/.netrc
if [[ -e "/config/.netrc" ]]; then
    # if the symlink already exists, remove it
    # create symlink
    ln -vs "/config/.netrc" "~/.netrc" > /dev/null 2>&1 || true
fi

# if /config/.cache exists, symlink to /home/dockeruser/.cache
if [[ -d "/config/.cache" ]]; then
    # if the symlink already exists, remove it
    if [[ -L "~/.cache/youtube-dl" && -d "~/.cache/youtube-dl" ]]; then
        rm -v "~/.cache/youtube-dl"
    fi
    # create symlink
    mkdir -p "~/.cache"
    ln -vs /config/.cache "~/.cache/youtube-dl"
fi

# if user has requested UPDATE_YOUTUBE_DL, then update youtube-dl
if [[ -n "$UPDATE_YOUTUBE_DL" ]]; then
    yt-dlp -U
fi

# Run yt-dlp with remainder of command line arguments
python3 /usr/local/bin/yt-dlp "$@"